<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Refit" Version="15.1.0" />
    <PackageReference Include="Refit.HttpClientFactory" Version="15.1.0" />
    <PackageReference Include="Refit.Reflection" Version="15.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\IntegratorAI.BuildingBlocks.Application\IntegratorAI.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\IntegratorAI.Providers.Contracts\IntegratorAI.Providers.Contracts.csproj" />
    <ProjectReference Include="..\IntegratorAI.Providers.Persistance\IntegratorAI.Providers.Persistence.csproj" />
  </ItemGroup>

</Project>
