CREATE TABLE [dbo].[Context]
(
	[Id]				UNIQUEIDENTIFIER	NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[Name]				NVARCHAR(255)		NOT NULL,
	[SystemRole]		NVARCHAR(MAX)		NOT NULL,
	[DomainContext]		NVARCHAR(MAX)		NULL,
	[DecisionPolicy]	NVARCHAR(MAX)		NULL,
	[OperatingRules]	NVARCHAR(MAX)		NULL,
	[OutputFormat]		NVARCHAR(MAX)		NULL,
	[CreatedAt]			DATETIME2			NOT NULL DEFAULT GETUTCDATE(),
)
