<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\IntegratorAI.BuildingBlocks.Application\IntegratorAI.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\Context\IntegratorAI.Context.Contracts\IntegratorAI.Context.Contracts.csproj" />
    <ProjectReference Include="..\..\Providers\IntegratorAI.Providers.Contracts\IntegratorAI.Providers.Contracts.csproj" />
    <ProjectReference Include="..\IntegratorAI.Chat.Contracts\IntegratorAI.Chat.Contracts.csproj" />
    <ProjectReference Include="..\IntegratorAI.Chat.Domain\IntegratorAI.Chat.Domain.csproj" />
  </ItemGroup>

</Project>
