<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Source\BuildingBlocks\IntegratorAI.BuildingBlocks.Domain\IntegratorAI.BuildingBlocks.Domain.csproj" />
    <ProjectReference Include="..\..\..\Source\BuildingBlocks\IntegratorAI.BuildingBlocks.Infrastructure\IntegratorAI.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Source\BuildingBlocks\IntegratorAI.BuildingBlocks.Persistence\IntegratorAI.BuildingBlocks.Persistence.csproj" />
    <ProjectReference Include="..\IntegratorAI.BuildingBlocks.Common\IntegratorAI.BuildingBlocks.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>